apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cast-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: cast.prod.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cast
                port:
                  number: 80
