apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cast-deploy.yaml
  - cast-ingress.yaml
  - cast-networkpolicy.yaml
  - cast-configmap.yaml
  - cast-secret.yaml
  

labels:
  - pairs:
      app.kubernetes.io/part-of: cast
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment: production
    includeSelectors: true
    includeTemplates: true
