
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast-cnpg

resources:
  - ../../../../bases/common/generators

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_ENV=qa-cnpg
      - DB_HOST=castdb
      - DB_PORT=5432
      - MESSAGE=Hello from QA cast-cnpg backend

secretGenerator:
  - name: db-secret
    behavior: merge
    literals:
      - username=cnpgqa
      - password=CNPGqaSecret!
