apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qa-cast-cnpg
  namespace: flux-system
spec:
  interval: 10m
  path: ./environments/qa/cast-cnpg/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cast-cnpg
  wait: true
