apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=info
      - FEATURE_FLAG=true

secretGenerator:
  - name: db-secret
    literals:
      - username=appuser
      - password=supersecret
generatorOptions:
  disableNameSuffixHash: true


