apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cast-common-config
    literals:
      - APP_NAME=cast
      - LOG_LEVEL=info
      - FEATURE_FLAG_UI=true
    options:
      disableNameSuffixHash: false

secretGenerator:
  - name: cast-common-secret
    literals:
      - COMMON_API_KEY=dummy-key
    type: Opaque
    options:
      disableNameSuffixHash: false

