# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - ../../../environments/prod/cast-cnpg
#   - cnpg-cluster.yaml
#   - cnpg-service.yaml
#   - cnpg-secret.yaml

# labels:
#   - pairs:
#       app.kubernetes.io/cluster: kva1gen-1
#       app.kubernetes.io/environment: prod
#     includeSelectors: true
