apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-cast-cnpg
  namespace: flux-system
spec:
  interval: 5m
  path: ./environments/prod/cast-cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cast-cnpg
  createNamespace: true
  wait: true
