apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast-cnpg

resources:
  - ../cast
  - namespace.yaml

patches:
  - path: backend-db-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: qa
      app.kubernetes.io/instance: cast-cnpg
    includeSelectors: true
