apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast

resources:
  - ../../../bases/prod/
  - ../../../bases/common/generators
  - ingress-frontend.yaml
  - ingress-backend.yaml
  - namespace.yaml

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml

configMapGenerator:
  - name: cast-prodconfig
    files:
      - configmap-env.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
      app.kubernetes.io/instance: cast
    includeSelectors: true

