apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast

resources:
  - ../../../bases/prod

patches:
  - path: image-replica-patch.yaml
  - path: configmap-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
      app.kubernetes.io/instance: cast
    includeSelectors: true
    includeTemplates: true
