apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast

resources:
  - ../../../bases/prod/

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: cast-app
    path: ingress-patch.yaml
  

labels:
  - pairs:
      app.kubernetes.io/environment: prod
      app.kubernetes.io/instance: cast
    includeSelectors: true