
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast

resources:
  - ../../../../bases/common/generators

configMapGenerator:
  - name: app-config
    behavior: merge #behavior: merge tells Kustomize to start from the base, then replace or add keys with these new values.
    literals:
      - APP_ENV=prod
      - BACKEND_URL=http://backend.prod.local
      - FRONTEND_THEME=dark

secretGenerator:
  - name: db-secret
    behavior: merge
    literals:
      - username=produser
      - password=ProdSuperSecret123

