- op: replace
  path: /metadata/annotations
  value:
    kubernetes.io/ingress.class: nginx

- op: replace
  path: /spec/rules
  value:
    - host: frontend.qa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cast-app
                port:
                  number: 80
