apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qa-cast
  namespace: flux-system
spec:
  interval: 5m
  path: ./environments/qa/cast
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cast
  createNamespace: true
  wait: true
