apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../environments/qa/cast/


labels:
  - pairs:
      app.kubernetes.io/cluster: kqde1gen-1
      app.kubernetes.io/environment: qa
    includeSelectors: true