apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../environments/qa/cast/

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: cast-app
    path: ingress-patch.yaml


labels:
  - pairs:
      app.kubernetes.io/cluster: kqde1gen-1
      app.kubernetes.io/environment: qa
    includeSelectors: true