apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deploy.yaml
  - frontend-service.yaml
  - backend-deploy.yaml
  - backend-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cast
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment: qa
    includeSelectors: true
    includeTemplates: true
