apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cast

resources:
  - ../../../bases/qa/

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml

configMapGenerator:
  - name: cast-config
    files:
      - configmap-env.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: qa
      app.kubernetes.io/instance: cast
    includeSelectors: true
